/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "main.h"
#include <stdbool.h>
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0        (GUI_ID_USER + 0x00)
#define ID_BUTTON_0        (GUI_ID_USER + 0x01)
#define ID_CHECKBOX_0        (GUI_ID_USER + 0x02)
#define ID_CHECKBOX_1        (GUI_ID_USER + 0x03)
#define ID_CHECKBOX_2        (GUI_ID_USER + 0x04)
#define ID_SLIDER_0        (GUI_ID_USER + 0x05)
#define ID_LISTVIEW_0        (GUI_ID_USER + 0x06)
#define ID_LISTVIEW_1        (GUI_ID_USER + 0x07)
#define ID_SLIDER_1        (GUI_ID_USER + 0x08)
#define ID_TEXT_0        (GUI_ID_USER + 0x09)
#define ID_TEXT_1        (GUI_ID_USER + 0x0A)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
extern struct status state;
extern uint32_t RBGcolor[2][2][2];
extern bool send_flag;//,music_flag,play_music_flag;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "LED", ID_BUTTON_0, 3, 6, 64, 70, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_0, 7, 141, 100, 50, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_1, 102, 141, 100, 50, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_2, 197, 141, 100, 50, 0, 0x0, 0 },
  { SLIDER_CreateIndirect, "Slider", ID_SLIDER_0, 10, 200, 250, 61, 0, 0x0, 0 },
  { LISTVIEW_CreateIndirect, "Listview", ID_LISTVIEW_0, 280, 0, 200, 136, 0, 0x0, 0 },
  { LISTVIEW_CreateIndirect, "Listview", ID_LISTVIEW_1, 280, 136, 200, 136, 0, 0x0, 0 },
  { SLIDER_CreateIndirect, "Slider", ID_SLIDER_1, 75, 26, 199, 50, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 78, 6, 196, 14, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_1, 45, 100, 201, 20, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
//void play_music(void);
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  uint16_t color_512=0x0000;
  GUI_COLOR color_512_24=0x000000;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'LED'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetText(hItem, "LED");
    //
    // Initialization of 'Checkbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
    CHECKBOX_SetText(hItem, "Red");
    //
    // Initialization of 'Checkbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1);
    CHECKBOX_SetText(hItem, "Green");
    //
    // Initialization of 'Checkbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_2);
    CHECKBOX_SetText(hItem, "Blue");
    //
    // Initialization of 'Listview'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
    LISTVIEW_AddRow(hItem, NULL);
    LISTVIEW_SetGridVis(hItem, 1);
    LISTVIEW_AddColumn(hItem, 200, "", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_SetHeaderHeight(hItem, 0);
    LISTVIEW_SetRowHeight(hItem, 136);
    //
    // Initialization of 'Listview'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_1);
    LISTVIEW_AddColumn(hItem, 200, "", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddRow(hItem, NULL);
    LISTVIEW_SetGridVis(hItem, 1);
    LISTVIEW_SetHeaderHeight(hItem, 0);
    LISTVIEW_SetRowHeight(hItem, 136);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetText(hItem, "0     1     2     3     4     5     6     7     8     9");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetText(hItem, "sjl 21211216  zxh 21211056");
    // USER START (Optionally insert additional code for further widget initialization)
    SLIDER_SetRange(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0), 0, 511);
    SLIDER_SetRange(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_1), 0, 9);
    SLIDER_SetNumTicks(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0), 0);
    SLIDER_SetNumTicks(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_1), 10);
    LISTVIEW_SetItemBkColor(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 0, 0, LISTVIEW_CI_UNSEL, GUI_BLACK);
    LISTVIEW_SetItemBkColor(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 0, 0, LISTVIEW_CI_SEL, GUI_BLACK);
    LISTVIEW_SetItemBkColor(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 0, 0, LISTVIEW_CI_SELFOCUS, GUI_BLACK);
    LISTVIEW_SetItemBkColor(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 0, 0, LISTVIEW_CI_DISABLED, GUI_BLACK);
    LISTVIEW_SetItemBkColor(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_1), 0, 0, LISTVIEW_CI_UNSEL, GUI_BLACK);
    LISTVIEW_SetItemBkColor(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_1), 0, 0, LISTVIEW_CI_SEL, GUI_BLACK);
    LISTVIEW_SetItemBkColor(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_1), 0, 0, LISTVIEW_CI_SELFOCUS, GUI_BLACK);
    LISTVIEW_SetItemBkColor(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_1), 0, 0, LISTVIEW_CI_DISABLED, GUI_BLACK);
    
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'LED'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        state.LED=!state.LED;
        HAL_GPIO_TogglePin(GPIOI, GPIO_PIN_1);
        send_flag=1;
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_0: // Notifications sent by 'Checkbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        state.RGB[0]=CHECKBOX_IsChecked(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0));
        LISTVIEW_SetItemBkColor(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 0, 0, LISTVIEW_CI_UNSEL, (GUI_COLOR)RBGcolor[state.RGB[0]][state.RGB[1]][state.RGB[2]]);
        LISTVIEW_SetItemBkColor(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 0, 0, LISTVIEW_CI_SEL, (GUI_COLOR)RBGcolor[state.RGB[0]][state.RGB[1]][state.RGB[2]]);
        LISTVIEW_SetItemBkColor(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 0, 0, LISTVIEW_CI_SELFOCUS, (GUI_COLOR)RBGcolor[state.RGB[0]][state.RGB[1]][state.RGB[2]]);
        LISTVIEW_SetItemBkColor(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 0, 0, LISTVIEW_CI_DISABLED, (GUI_COLOR)RBGcolor[state.RGB[0]][state.RGB[1]][state.RGB[2]]);
        send_flag=1;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_1: // Notifications sent by 'Checkbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        state.RGB[1]=CHECKBOX_IsChecked(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1));
        LISTVIEW_SetItemBkColor(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 0, 0, LISTVIEW_CI_UNSEL, (GUI_COLOR)RBGcolor[state.RGB[0]][state.RGB[1]][state.RGB[2]]);
        LISTVIEW_SetItemBkColor(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 0, 0, LISTVIEW_CI_SEL, (GUI_COLOR)RBGcolor[state.RGB[0]][state.RGB[1]][state.RGB[2]]);
        LISTVIEW_SetItemBkColor(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 0, 0, LISTVIEW_CI_SELFOCUS, (GUI_COLOR)RBGcolor[state.RGB[0]][state.RGB[1]][state.RGB[2]]);
        LISTVIEW_SetItemBkColor(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 0, 0, LISTVIEW_CI_DISABLED, (GUI_COLOR)RBGcolor[state.RGB[0]][state.RGB[1]][state.RGB[2]]);
        send_flag=1;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CHECKBOX_2: // Notifications sent by 'Checkbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        state.RGB[2]=CHECKBOX_IsChecked(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_2));
        LISTVIEW_SetItemBkColor(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 0, 0, LISTVIEW_CI_UNSEL, (GUI_COLOR)RBGcolor[state.RGB[0]][state.RGB[1]][state.RGB[2]]);
        LISTVIEW_SetItemBkColor(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 0, 0, LISTVIEW_CI_SEL, (GUI_COLOR)RBGcolor[state.RGB[0]][state.RGB[1]][state.RGB[2]]);
        LISTVIEW_SetItemBkColor(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 0, 0, LISTVIEW_CI_SELFOCUS, (GUI_COLOR)RBGcolor[state.RGB[0]][state.RGB[1]][state.RGB[2]]);
        LISTVIEW_SetItemBkColor(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 0, 0, LISTVIEW_CI_DISABLED, (GUI_COLOR)RBGcolor[state.RGB[0]][state.RGB[1]][state.RGB[2]]);
        send_flag=1;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SLIDER_0: // Notifications sent by 'Slider'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        color_512=SLIDER_GetValue(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0));
        state.color[0]=color_512>>6;
        state.color[1]=(color_512>>3)&0x0007;
        state.color[2]=color_512&0x0007;
        color_512_24=(state.color[0]<<21)|(state.color[1]<<13)|(state.color[2]<<5);
        LISTVIEW_SetItemBkColor(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_1), 0, 0, LISTVIEW_CI_UNSEL, color_512_24);
        LISTVIEW_SetItemBkColor(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_1), 0, 0, LISTVIEW_CI_SEL, color_512_24);
        LISTVIEW_SetItemBkColor(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_1), 0, 0, LISTVIEW_CI_SELFOCUS, color_512_24);
        LISTVIEW_SetItemBkColor(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_1), 0, 0, LISTVIEW_CI_DISABLED, color_512_24);
        send_flag=1;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTVIEW_0: // Notifications sent by 'Listview'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTVIEW_1: // Notifications sent by 'Listview'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SLIDER_1: // Notifications sent by 'Slider'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
          state.num=SLIDER_GetValue(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_1));
          SLIDER_SetValue(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_1),state.num);
          send_flag=1;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
